source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.6'

use_frameworks!

target 'QuickTableView_Example' do
  pod 'QuickTableView', :path => '../'

  target 'QuickTableView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0'
  end
end

pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      config.build_settings.delete('TARGETED_DEVICE_FAMILY')
      config.build_settings.delete('SWIFT_VERSION')
      config.build_settings.delete('ARCH')
    end
  end
end
