source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QuickTableView_Example', :exclusive => true do
  pod 'QuickTableView', :path => '../'
end

target 'QuickTableView_Tests', :exclusive => true do
  pod 'QuickTableView', :path => '../'

  pod 'Quick', '~> 0.9.2'
  pod 'Nimble', '~> 4.0.0'
end
