source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QuickTableView_Example' do
  pod 'QuickTableView', :path => '../'

  target 'QuickTableView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.1'
  end
end

pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
